2019-01-28 11:19:36 logger.py(82 - MainProcess - MainThread - <module>): ERROR list index out of range
Traceback (most recent call last):
  File "C:\Users\tanglei\PycharmProjects\logging\common\logger.py", line 80, in <module>
    print a[2]
IndexError: list index out of range
